# Generated by Django 3.1.2 on 2021-02-22 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crashAnalyzer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collisionlocation',
            name='lattitude',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='collisionlocation',
            name='location',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='collisionlocation',
            name='longitude',
            field=models.CharField(max_length=250),
        ),
    ]
