# Generated by Django 3.1.2 on 2021-02-22 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crashAnalyzer', '0002_auto_20210222_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impactedpeople',
            name='collisionId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collision_Id', to='crashAnalyzer.collisionlocation'),
        ),
    ]
