# Generated by Django 3.1.2 on 2021-02-22 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crashAnalyzer', '0003_auto_20210222_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impactedpeople',
            name='collisionId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crashAnalyzer.collisionlocation'),
        ),
    ]
