# Generated by Django 3.1.2 on 2021-02-22 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crashAnalyzer', '0004_auto_20210222_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collisionlocation',
            name='collisionId',
            field=models.CharField(max_length=250, primary_key=True, serialize=False, unique=True),
        ),
    ]
