# Generated by Django 3.1.2 on 2021-02-24 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crashAnalyzer', '0006_bikestations'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BikeStations',
        ),
    ]
