# Generated by Django 3.1.2 on 2021-02-26 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crashAnalyzer', '0009_googlemapapikey'),
    ]

    operations = [
        migrations.AddField(
            model_name='bikestation',
            name='nearestCrashDistance',
            field=models.FloatField(default=0, max_length=250),
        ),
        migrations.AddField(
            model_name='bikestation',
            name='nearestCrashLocName',
            field=models.CharField(default='Location Not Available', max_length=250),
        ),
    ]
