# Generated by Django 3.1.2 on 2021-02-26 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crashAnalyzer', '0010_auto_20210226_1847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bikestation',
            name='nearestCrashDistance',
        ),
        migrations.RemoveField(
            model_name='bikestation',
            name='nearestCrashLocName',
        ),
    ]
